### ISSUE TITLE
Issues with latest version of CustomNPC+

### ISSUE THREAD

**Issue by tester2024** [AntonIT99/Flans-Mod-NPC-Vehicles#10]
```LOG
[22:57:02] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: NpcNavRange
	at noppes.npcs.entity.EntityNPCInterface.func_110147_ax(EntityNPCInterface.java:288) ~[EntityNPCInterface.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:120) ~[sv.class:?]
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:91) ~[sw.class:?]
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23) ~[td.class:?]
	at noppes.npcs.entity.EntityNPCInterface.<init>(EntityNPCInterface.java:243) ~[EntityNPCInterface.class:?]
	at noppes.npcs.entity.EntityNPCFlying.<init>(EntityNPCFlying.java:13) ~[EntityNPCFlying.class:?]
	at noppes.npcs.entity.EntityCustomNpc.<init>(EntityCustomNpc.java:27) ~[EntityCustomNpc.class:?]
	at noppes.npcs.items.ItemNpcWand.func_77648_a(ItemNpcWand.java:46) ~[ItemNpcWand.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded content pack: Flans-Simple-Parts-Pack-1.7.10.jar
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded content pack: Flans-World-War-Two-Pack-1.7.10.jar
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded content pack: Machetemen-Arms-Pack-Mod-Forge-1.7.10.jar
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded content pack: Manus-WW2-Content-Pack-Forge-1.7.10.zip
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded content pack: Modern Warfare-Content Pack-1.7.10-4.10.0.jar
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded content pack: Warfare44ContentPack- Version 3.2.jar
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded content pack: Zombie-Content Pack-1.7.10-4.10.0.jar
[22:57:02] [Server thread/INFO] [Flan's Mod Ultimate]: Loaded textures and models.
[22:57:03] [Server thread/ERROR]: This crash report has been saved to: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\crash-reports\crash-2023-07-30_22.57.02-server.txt
[22:57:03] [Server thread/INFO]: Stopping server
[22:57:03] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/30/23 10:57 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: NpcNavRange
	at noppes.npcs.entity.EntityNPCInterface.func_110147_ax(EntityNPCInterface.java:288)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:120)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:91)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
	at noppes.npcs.entity.EntityNPCInterface.<init>(EntityNPCInterface.java:243)
	at noppes.npcs.entity.EntityNPCFlying.<init>(EntityNPCFlying.java:13)
	at noppes.npcs.entity.EntityCustomNpc.<init>(EntityCustomNpc.java:27)
	at noppes.npcs.items.ItemNpcWand.func_77648_a(ItemNpcWand.java:46)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5767642584 bytes (5500 MB) / 7955021824 bytes (7586 MB) up to 7955021824 bytes (7586 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	OpenEye{0.8} [OpenEye] (OpenEye.jar) 
	UCHIJAAAA	flagmod{1.0} [Flag Mod] ([1.7.10] Flag-Mod-1.0.jar) 
	UCHIJAAAA	customnpcs{1.8.5} [CustomNPC+] (CustomNPC-Plus-1.8.5.jar) 
	UCHIJAAAA	flansmod{1.57} [Flan's Mod Ultimate] (Flans_Mod_Ultimate_Stability_Edition-1.57.jar) 
	UCHIJAAAA	npcflancompatibility{1.0} [CustomNPCs Flan Compatibility Mod] ([1.7.10]-Flan's-Mod-NPC-Vehicles-4.0.jar) 
	UCHIJAAAA	wolffsmod{4.0} [Flan's Mod NPC Vehicles] ([1.7.10]-Flan's-Mod-NPC-Vehicles-4.0.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4648)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4648].jar) 
	UCHIJAAAA	replaymod-restrictions{1.7.10-2.5.2} [Replay Mod - Restrictions] (replaymod-1.7.10-2.5.2.jar) 
	UCHIJAAAA	replaymod{1.7.10-2.5.2} [Replay Mod] (replaymod-1.7.10-2.5.2.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Flan's Mod Content Packs: 
Flans-Simple-Parts-Pack-1.7.10.jar (filepath: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\Flan\Flans-Simple-Parts-Pack-1.7.10.jar)
Flans-World-War-Two-Pack-1.7.10.jar (filepath: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\Flan\Flans-World-War-Two-Pack-1.7.10.jar)
Machetemen-Arms-Pack-Mod-Forge-1.7.10.jar (filepath: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\Flan\Machetemen-Arms-Pack-Mod-Forge-1.7.10.jar)
Manus-WW2-Content-Pack-Forge-1.7.10.zip (filepath: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\Flan\Manus-WW2-Content-Pack-Forge-1.7.10.zip)
Modern Warfare-Content Pack-1.7.10-4.10.0.jar (filepath: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\Flan\Modern Warfare-Content Pack-1.7.10-4.10.0.jar)
Warfare44ContentPack- Version 3.2.jar (filepath: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\Flan\Warfare44ContentPack- Version 3.2.jar)
Zombie-Content Pack-1.7.10-4.10.0.jar (filepath: C:\Games\MultiMC\instances\NPC 1.7.10\.minecraft\Flan\Zombie-Content Pack-1.7.10-4.10.0.jar)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['MHProDevRec'/52, l='New World', x=-1279.14, y=64.00, z=790.86]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 536.40
	OpenGlRenderer: NVIDIA GeForce RTX 4080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 24
````

im getting this error then game crash

installed mods:

![image](https://github.com/AntonIT99/Flans-Mod-NPC-Vehicles/assets/124782291/e2775501-dc50-4522-bf59-188a48b06956)
![image](https://github.com/AntonIT99/Flans-Mod-NPC-Vehicles/assets/124782291/9806cb5c-575a-4e82-a877-ba9b4ad32d22)

**Comment by tester2024** [comment]
[crash-2023-07-30_22.50.33-server.txt](https://github.com/AntonIT99/Flans-Mod-NPC-Vehicles/files/12209953/crash-2023-07-30_22.50.33-server.txt)

**Comment by Price-MA-Butta** [comment]
Hello, this issue is being worked on. For now, use custom npcs + 1.7 or change the name of wolfs mod so it is alphabetically higher than custom npcs plus.

https://discord.gg/BrZF5bn3ZY Here is the discord incase you are not here already.

**Comment by AntonIT99** [comment]
Hi,
sorry for the inconvenience, the release 4.0 of my mod was not compatible of newest versions of Custom NPC+, it only functioned with CNPC+ 1.7. Now the mod has been updated to the release 5.0 which fully supports CNPC+ 1.8.6. Download the latest release (https://www.curseforge.com/minecraft/mc-mods/flans-mod-npc-vehicles/files) and this should fix your problem.
