### ISSUE TITLE
crash when enabling NPC Vehicle setting in inventory (NoSuchFieldError: health)

### ISSUE THREAD

**Issue by themcjarhead** [AntonIT99/Flans-Mod-NPC-Vehicles#17]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/27/24 4:50 PM
Description: Updating screen events

java.lang.NoSuchFieldError: health
	at noppes.npcs.DataInventory.lambda$setDriveableStats$0(DataInventory.java:647)
	at noppes.npcs.DataInventory$$Lambda$59/145823348.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
	at noppes.npcs.DataInventory.setDriveableStats(DataInventory.java:647)
	at noppes.npcs.DataInventory.handler$onSetWeapons$zzd000(DataInventory.java:600)
	at noppes.npcs.DataInventory.setWeapons(DataInventory.java:70)
	at noppes.npcs.client.gui.mainmenu.GuiNPCInv.handler$onActionPerformed$zzj001(GuiNPCInv.java:574)
	at noppes.npcs.client.gui.mainmenu.GuiNPCInv.func_146284_a(GuiNPCInv.java:109)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
	at noppes.npcs.client.gui.util.GuiContainerNPCInterface.func_73864_a(GuiContainerNPCInterface.java:97)
	at noppes.npcs.client.gui.util.GuiContainerNPCInterface2.func_73864_a(GuiContainerNPCInterface2.java:45)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at noppes.npcs.DataInventory.lambda$setDriveableStats$0(DataInventory.java:647)
	at noppes.npcs.DataInventory$$Lambda$59/145823348.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
	at noppes.npcs.DataInventory.setDriveableStats(DataInventory.java:647)
	at noppes.npcs.DataInventory.handler$onSetWeapons$zzd000(DataInventory.java:600)
	at noppes.npcs.DataInventory.setWeapons(DataInventory.java:70)
	at noppes.npcs.client.gui.mainmenu.GuiNPCInv.handler$onActionPerformed$zzj001(GuiNPCInv.java:574)
	at noppes.npcs.client.gui.mainmenu.GuiNPCInv.func_146284_a(GuiNPCInv.java:109)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
	at noppes.npcs.client.gui.util.GuiContainerNPCInterface.func_73864_a(GuiContainerNPCInterface.java:97)
	at noppes.npcs.client.gui.util.GuiContainerNPCInterface2.func_73864_a(GuiContainerNPCInterface2.java:45)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)

-- Affected screen --
Details:
	Screen name: noppes.npcs.client.gui.mainmenu.GuiNPCInv

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['TheMCJarhead'/106, l='MpServer', x=1032.27, y=5.62, z=-1180.30]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (909,4,-1306), Chunk: (at 13,0,6 in 56,-82; contains blocks 896,0,-1312 to 911,255,-1297), Region: (1,-3; contains chunks 32,-96 to 63,-65, blocks 512,0,-1536 to 1023,255,-1025)
	Level time: 246151 game time, 63893 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntitySeat['entity.Seat.name'/98, l='MpServer', x=1038.04, y=5.50, z=-1175.62], EntitySeat['entity.Seat.name'/99, l='MpServer', x=1036.36, y=6.38, z=-1175.32], EntitySeat['entity.Seat.name'/100, l='MpServer', x=1038.26, y=4.63, z=-1175.96], EntityClientPlayerMP['TheMCJarhead'/106, l='MpServer', x=1032.27, y=5.62, z=-1180.30], EntityWheel['entity.Wheel.name'/101, l='MpServer', x=1034.25, y=4.00, z=-1175.93], EntityCustomNpc['Milan'/70, l='MpServer', x=1034.50, y=4.00, z=-1181.50], EntityWheel['entity.Wheel.name'/102, l='MpServer', x=1034.97, y=4.00, z=-1173.79], EntityWheel['entity.Wheel.name'/103, l='MpServer', x=1038.75, y=4.00, z=-1175.07], EntityWheel['entity.Wheel.name'/104, l='MpServer', x=1038.03, y=4.00, z=-1177.21], EntityCustomNpc['Bofors AA Gun'/76, l='MpServer', x=1042.50, y=4.00, z=-1161.50], EntityCustomNpc['Bofors AA Gun'/78, l='MpServer', x=1061.50, y=4.00, z=-1132.50], EntityCamera['unknown'/913, l='MpServer', x=1036.50, y=4.63, z=-1175.50], EntityCustomNpc['Bofors AA Gun'/49, l='MpServer', x=1021.50, y=4.00, z=-1135.50], EntityVehicle['Type 97 Chi-Ha'/62, l='MpServer', x=1036.50, y=4.63, z=-1175.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1396720944 bytes (1332 MB) / 3815768064 bytes (3639 MB) up to 4951375872 bytes (4722 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5312m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	extendedshaders{6.0} [Extended Shaders] ([1.7.10] Extended Shaders 6.0.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	customnpcs{1.8.6} [CustomNPC+] (CustomNPC-Plus-1.8.6.jar) 
	UCHIJAAAA	flansmod{LabJac Mod Mark 25843 - February 2021} [Flan's Mod LabJac Edition] (flansmodfobversion.jar) 
	UCHIJAAAA	wolffsmod{6.0.2} [Flan's Mod NPC Vehicles] ([1.7.10] Flan's Mod NPC Vehicles-6.0.2.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJAAAA	creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
	UCHIJAAAA	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJAAAA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic Lights-1.3.9a-MC1.7.10.jar) 
	UCHIJAAAA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJAAAA	erde{1.0c} [Entity Render Extender] (EntityRenderDistanceExtender-1.0c.jar) 
	UCHIJAAAA	l4j_jndi_fix{1.0.0} [Log4J2 JNDI Fix] (l4j_jndi_fix-oldforge-1.0.0.jar) 
	UCHIJAAAA	MapWriter{2.1.8} [MapWriter] (MapWriter-1.7.10-2.1.10.jar) 
	UCHIJAAAA	Monoblocks{11.6} [§cMonoblocks] (Monoblocks-11.6.jar) 
	UCHIJAAAA	MonoblocksMultipart{11.6} [MonoblocksMultipart] (Monoblocks-11.6.jar) 
	UCHIJAAAA	neodymium{0.1.8.4} [Neodymium] (neodymium-1.7.10-0.1.8.4.jar) 
	UCHIJAAAA	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.65' Renderer: 'NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

**Comment by themcjarhead** [comment]
It seems like it might just be the version of flans mod I'm using, if there's anything specific that can be done to fix it myself I'd also like to know.

**Comment by AntonIT99** [comment]
It's due to the version of Flan's Mod
